# 02 — Trích xuất đặc trưng (Feature Engineering)

Tạo cột Vùng miền, gom nhóm dân tộc, bóc tách & geocode địa chỉ, xử lý mã ICD thành các nhóm bệnh. **Đầu vào**: `data/processed/01_cleaned.pkl`. **Kết quả**: `data/processed/model_df.{pkl,csv}` cho EDA & Modeling.

> ⚠️ Cell geocoding gọi API Nominatim (~1 req/giây) nên có thể mất ~20 phút.

### Import & nạp dữ liệu đã làm sạch

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import config

In [ ]:
df = pd.read_pickle(config.CLEANED_PKL)
df.head()

- Tạo một cột Miền địa lý để xem tỉnh nào thuộc miền nào

In [40]:
def region(provinces):
  regions_dict = {
    "Đồng bằng sông Hồng": ["HÀ NỘI", "HẢI PHÒNG", "HẢI DƯƠNG", "HƯNG YÊN", "HÀ NAM", "NAM ĐỊNH", "THÁI BÌNH", "NINH BÌNH", "VĨNH PHÚC", "BẮC NINH"],
    "Trung du và miền núi phía Bắc": ["LÀO CAI", "ĐIỆN BIÊN", "LAI CHÂU", "SƠN LA", "YÊN BÁI", "HÒA BÌNH", "CAO BẰNG", "BẮC KẠN",
                                      "HÀ GIANG", "TUYÊN QUANG", "THÁI NGUYÊN", "LẠNG SƠN", "BẮC GIANG", "PHÚ THỌ", "QUẢNG NINH"],
    "Bắc Trung Bộ": ["THANH HÓA", "NGHỆ AN", "HÀ TĨNH", "QUẢNG BÌNH", "QUẢNG TRỊ", "THỪA THIÊN - HUẾ"],
    "Nam Trung Bộ": ["ĐÀ NẴNG", "QUẢNG NAM", "QUẢNG NGÃI", "BÌNH ĐỊNH", "PHÚ YÊN", "KHÁNH HÒA", "NINH THUẬN", "BÌNH THUẬN"],
    "Tây Nguyên": ["KON TUM", "GIA LAI", "ĐẮK LẮK", "ĐẮK NÔNG", "LÂM ĐỒNG"],
    "Đông Nam Bộ": ["TP. HỒ CHÍ MINH", "BÌNH DƯƠNG", "ĐỒNG NAI", "BÀ RỊA - VŨNG TÀU", "TÂY NINH", "BÌNH PHƯỚC"],
    "Đồng bằng sông Cửu Long": ["CẦN THƠ", "LONG AN", "TIỀN GIANG", "BẾN TRE", "VĨNH LONG", "ĐỒNG THÁP", "AN GIANG", "KIÊN GIANG", "HẬU GIANG", "SÓC TRĂNG", "BẠC LIÊU", "CÀ MAU", "TRÀ VINH"]
  }
  regions = []
  for province in provinces:
    for region, province_list in regions_dict.items():
      if province in province_list:
        regions.append(region)
  return regions

df['Vùng miền'] = region(df['TENTINHTHANH'])

**Đếm số lượt khám theo từng vùng miền** để biết bệnh nhân chủ yếu đến từ đâu.

In [41]:
df['Vùng miền'].value_counts()

Vùng miền
Nam Trung Bộ                     64184
Tây Nguyên                        3298
Đông Nam Bộ                        223
Đồng bằng sông Hồng                144
Bắc Trung Bộ                       114
Đồng bằng sông Cửu Long             50
Trung du và miền núi phía Bắc       23
Name: count, dtype: int64

- Bây giờ đến bước xử lí cột DANTOC, có tổng cộng 27 dân tộc (tính cả người nước ngoài)

In [42]:
ethnicity = df['DANTOC'].unique()
print(ethnicity)
print(len(ethnicity))

<ArrowStringArray>
[      'Kinh',      'Ba na',       'Chăm',        'Lào',       'Ê đê',
     'M nông',      'La hù', 'Nước ngoài',      'Lô lô',       'H rê',
    'Gia rai',      'La ha',     'La chí',       'Nùng',    'X tiêng',
         'Lự',        'Tày',     'Hà nhì',        'Thổ',     'H mông',
      'Mường',       'Chứt',       'K tu',       'Thái',    'Xơ đăng',
        'Hoa',        'Dao']
Length: 27, dtype: str
27

In [43]:
df['DANTOC'] = list(map(lambda x: x if (x == 'Kinh' or x == 'Nước ngoài') else 'Dân tộc thiểu số',df['DANTOC']))

**Xem lại dữ liệu** sau khi đã gom nhóm dân tộc.

In [44]:
df

,Tuổi,DANTOC,TENPXA,TENQUANHUYEN,TENTINHTHANH,MAICD,CHANDOAN,NGAYVAO,NGAYRA,TONGCP,BHYT_TT,Thời gian điều trị,Vùng miền
0,28,Kinh,PHƯỜNG NHƠN BÌNH,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,S01.1;,Vết thương hở của mi mắt và vùng quanh mắt;,2016-01-01 00:55:00,2016-01-01 01:04:00,1.500000e+04,0.000000e+00,0.006250,Nam Trung Bộ
1,18,Kinh,PHƯỜNG NHƠN PHÚ,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,I20;,Cơn đau thắt ngực;,2016-01-01 01:37:00,2016-01-01 03:23:00,8.334650e+04,8.334650e+04,0.073611,Nam Trung Bộ
2,36,Kinh,XÃ NHƠN LỘC,THỊ XÃ AN NHƠN,BÌNH ĐỊNH,J68.2;P71.0;,Viêm hô hấp trên;Hạ calci máu;,2016-01-01 03:31:00,2016-01-01 05:00:00,1.599990e+02,0.000000e+00,0.061806,Nam Trung Bộ
3,5,Kinh,PHƯỜNG TRẦN QUANG DIỆU,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,A91.A;,Sốt xuất huyết Dengue;,2015-12-29 20:25:00,2016-01-01 07:00:00,1.129380e+05,1.129380e+05,2.440972,Nam Trung Bộ
4,5,Kinh,PHƯỜNG NHƠN PHÚ,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,A91;J00;,Sốt xuất huyết Dengue;Viêm Họng Cấp;,2015-12-25 08:44:00,2016-01-01 07:00:00,2.623950e+05,2.623950e+05,6.927778,Nam Trung Bộ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68757,73,Kinh,PHƯỜNG TRẦN QUANG DIỆU,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,Y84.1;D63.0;,Chạy thận nhân tạo;Thiếu máu trong bệnh suy th...,2016-12-01 08:11:00,2016-12-31 23:00:00,1.102239e+07,1.102239e+07,30.617361,Nam Trung Bộ
68758,24,Dân tộc thiểu số,PHƯỜNG BÌNH ĐỊNH,THỊ XÃ AN NHƠN,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:53:00,2016-12-31 23:00:00,1.359227e+07,1.359227e+07,42.671528,Nam Trung Bộ
68759,42,Kinh,XÃ NHƠN PHÚC,THỊ XÃ AN NHƠN,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:52:00,2016-12-31 23:00:00,1.021012e+07,1.021012e+07,42.672222,Nam Trung Bộ
68760,40,Kinh,XÃ MỸ THỌ,HUYỆN PHÙ MỸ,BÌNH ĐỊNH,Y84.1;J18;,Chạy thận nhân tạo;Viêm phổi;,2016-11-10 06:56:00,2016-12-31 23:00:00,1.734061e+07,1.734061e+07,51.669444,Nam Trung Bộ
68761,58,Kinh,PHƯỜNG ĐỐNG ĐA,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,I67;,Bệnh mạch máu não khác;,2016-12-31 22:26:00,2016-12-31 23:47:00,1.500000e+04,0.000000e+00,0.056250,Nam Trung Bộ

**Khảo sát tiền tố tên Phường/Xã**: tách từ đầu tiên (PHƯỜNG, XÃ, THỊ TRẤN…) và đếm tần suất để biết cách bóc tách tên thuần.

In [45]:
df['TENPXA'].str.split(' ').str[0].value_counts()

TENPXA
XÃ        38166
PHƯỜNG    23976
THỊ        4586
PHƯỚC       402
TÂN         180
TT          163
KHÔNG        86
CƯ           84
ĐAK          76
HÀ           63
P.XUÂN       58
TÂY          50
HÒA          43
HOÀ          36
DĂK          14
BÌNH         10
HOÀNG         9
NAM           7
XÃ           4
PHÚ           4
ĐĂK           4
ĐẮK           3
HỒNG          2
H             1
SƠN           1
TRẢNG         1
NHƠN          1
LONG          1
XUÂN          1
ĐIỆN          1
XẢ            1
K             1
SÔNG          1
Name: count, dtype: int64

**Bóc tách tên Phường/Xã thuần** từ `TENPXA` (làm trên bản sao `df1`): bỏ tiền tố hành chính — PHƯỜNG/XÃ/TT/XẢ bỏ 1 từ; THỊ TRẤN bỏ 2 từ; xử lý riêng trường hợp `P.XUÂN`.

In [46]:
df1 = df.copy()
df1['Phường/Xã'] = list(map(lambda x: ' '.join(x.split(' ')[1:]) if (x.split(' ')[0] in ['PHƯỜNG','XÃ','TT','XẢ']) else
                                      ' '.join(x.split(' ')[2:]) if (x.split(' ')[0] == 'THỊ') else
                                      ' '.join(['XUÂN'] + x.split(' ')[1:]) if (x.split(' ')[0] == 'P.XUÂN') else x,df1['TENPXA']))

**Xử lý phường đánh số**: với tên phường chỉ gồm chữ số (vd '1', '2'), thêm tiền tố `'PHƯỜNG '` để tên có nghĩa (PHƯỜNG 1, PHƯỜNG 2…).

In [47]:
#df1[df1['Phường/Xã'].str.isdigit()]['TENPXA'].str.split(" ").str[0].value_counts()
df1['Phường/Xã'] = list(map(lambda x: 'PHƯỜNG ' + x if x.isdigit() else x,df1['Phường/Xã']))

**Đếm số Phường/Xã** duy nhất sau khi chuẩn hóa, để kiểm tra mức độ rút gọn.

In [48]:
df1['Phường/Xã'].nunique()

1054

**Khảo sát tiền tố tên Quận/Huyện** (HUYỆN, TP, THÀNH PHỐ, THỊ XÃ…) tương tự bước xử lý Phường/Xã.

In [49]:
df1['TENQUANHUYEN'].str.split(' ').str[0].value_counts()

TENQUANHUYEN
HUYỆN    37134
THÀNH    22220
THỊ       8393
QUẬN       237
TP          28
TX           9
HOÀNG        9
LỘC          2
PHÚ          2
BUÔN         1
CHÂU         1
Name: count, dtype: int64

**Bóc tách tên Huyện/TP thuần** từ `TENQUANHUYEN`: bỏ tiền tố HUYỆN/TP/TX (1 từ) hoặc THÀNH PHỐ/THỊ XÃ (2 từ).

In [50]:
df1['Huyện/TP'] = list(map(lambda x: ' '.join(x.split(' ')[1:]) if (x.split(' ')[0] in ['HUYỆN','TP','TX']) else
                                     ' '.join(x.split(' ')[2:]) if (x.split(' ')[0] in ['THÀNH','THỊ']) else x,df1['TENQUANHUYEN']))

**Xem lại dữ liệu** với hai cột địa danh đã chuẩn hóa (`Phường/Xã`, `Huyện/TP`).

In [51]:
df1

,Tuổi,DANTOC,TENPXA,TENQUANHUYEN,TENTINHTHANH,MAICD,CHANDOAN,NGAYVAO,NGAYRA,TONGCP,BHYT_TT,Thời gian điều trị,Vùng miền,Phường/Xã,Huyện/TP
0,28,Kinh,PHƯỜNG NHƠN BÌNH,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,S01.1;,Vết thương hở của mi mắt và vùng quanh mắt;,2016-01-01 00:55:00,2016-01-01 01:04:00,1.500000e+04,0.000000e+00,0.006250,Nam Trung Bộ,NHƠN BÌNH,QUI NHƠN
1,18,Kinh,PHƯỜNG NHƠN PHÚ,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,I20;,Cơn đau thắt ngực;,2016-01-01 01:37:00,2016-01-01 03:23:00,8.334650e+04,8.334650e+04,0.073611,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN
2,36,Kinh,XÃ NHƠN LỘC,THỊ XÃ AN NHƠN,BÌNH ĐỊNH,J68.2;P71.0;,Viêm hô hấp trên;Hạ calci máu;,2016-01-01 03:31:00,2016-01-01 05:00:00,1.599990e+02,0.000000e+00,0.061806,Nam Trung Bộ,NHƠN LỘC,AN NHƠN
3,5,Kinh,PHƯỜNG TRẦN QUANG DIỆU,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,A91.A;,Sốt xuất huyết Dengue;,2015-12-29 20:25:00,2016-01-01 07:00:00,1.129380e+05,1.129380e+05,2.440972,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN
4,5,Kinh,PHƯỜNG NHƠN PHÚ,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,A91;J00;,Sốt xuất huyết Dengue;Viêm Họng Cấp;,2015-12-25 08:44:00,2016-01-01 07:00:00,2.623950e+05,2.623950e+05,6.927778,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68757,73,Kinh,PHƯỜNG TRẦN QUANG DIỆU,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,Y84.1;D63.0;,Chạy thận nhân tạo;Thiếu máu trong bệnh suy th...,2016-12-01 08:11:00,2016-12-31 23:00:00,1.102239e+07,1.102239e+07,30.617361,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN
68758,24,Dân tộc thiểu số,PHƯỜNG BÌNH ĐỊNH,THỊ XÃ AN NHƠN,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:53:00,2016-12-31 23:00:00,1.359227e+07,1.359227e+07,42.671528,Nam Trung Bộ,BÌNH ĐỊNH,AN NHƠN
68759,42,Kinh,XÃ NHƠN PHÚC,THỊ XÃ AN NHƠN,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:52:00,2016-12-31 23:00:00,1.021012e+07,1.021012e+07,42.672222,Nam Trung Bộ,NHƠN PHÚC,AN NHƠN
68760,40,Kinh,XÃ MỸ THỌ,HUYỆN PHÙ MỸ,BÌNH ĐỊNH,Y84.1;J18;,Chạy thận nhân tạo;Viêm phổi;,2016-11-10 06:56:00,2016-12-31 23:00:00,1.734061e+07,1.734061e+07,51.669444,Nam Trung Bộ,MỸ THỌ,PHÙ MỸ
68761,58,Kinh,PHƯỜNG ĐỐNG ĐA,THÀNH PHỐ QUI NHƠN,BÌNH ĐỊNH,I67;,Bệnh mạch máu não khác;,2016-12-31 22:26:00,2016-12-31 23:47:00,1.500000e+04,0.000000e+00,0.056250,Nam Trung Bộ,ĐỐNG ĐA,QUI NHƠN

**Tạo bảng địa chỉ duy nhất** `df2`: lấy các tổ hợp (Phường/Xã, Huyện/TP, Tỉnh) không trùng và ghép thành chuỗi `'Địa chỉ'` đầy đủ (bỏ phần Phường/Xã nếu là `KHÔNG XÁC ĐỊNH`). Đây là bước chuẩn bị để **lấy tọa độ (geocode) và join với `address_df_full.csv`** ở phần tiếp theo.

In [52]:
df2 = df1[['Phường/Xã','Huyện/TP','TENTINHTHANH']].drop_duplicates()
df2['Địa chỉ'] = list(map(lambda x,y,z: x + ',' + y + ',' + z if (x != 'KHÔNG XÁC ĐỊNH') else
                                   y + ',' + z, df2['Phường/Xã'], df2['Huyện/TP'], df2['TENTINHTHANH']))
df2.reset_index(drop = True, inplace = True)
df2

,Phường/Xã,Huyện/TP,TENTINHTHANH,Địa chỉ
0,NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH,"NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH"
1,NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH"
2,NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH,"NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH"
3,TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH"
4,DIÊU TRÌ,TUY PHƯỚC,BÌNH ĐỊNH,"DIÊU TRÌ,TUY PHƯỚC,BÌNH ĐỊNH"
...,...,...,...,...
1252,ĐÔNG THẠNH,CẦN GIUỘC,LONG AN,"ĐÔNG THẠNH,CẦN GIUỘC,LONG AN"
1253,THANH TRÌ,THANH TRÌ,HÀ NỘI,"THANH TRÌ,THANH TRÌ,HÀ NỘI"
1254,LỘC THỦY,PHÚ LỘC,THỪA THIÊN - HUẾ,"LỘC THỦY,PHÚ LỘC,THỪA THIÊN - HUẾ"
1255,VĨNH THANH,RẠCH GIÁ,KIÊN GIANG,"VĨNH THANH,RẠCH GIÁ,KIÊN GIANG"
1256,PHƯỜNG 3,QUẬN 10,TP. HỒ CHÍ MINH,"PHƯỜNG 3,QUẬN 10,TP. HỒ CHÍ MINH"

**Lấy tọa độ trực tiếp qua API geocoding (thay vì đọc `address_df_full.csv` có sẵn).**

Dùng dịch vụ **Nominatim (OpenStreetMap)** qua thư viện `geopy` — miễn phí, không cần API key. Với mỗi địa chỉ duy nhất trong `df2`, ta truy vấn tọa độ theo 2 mức:

- **level 1**: tìm thấy theo địa chỉ đầy đủ (Phường/Xã, Huyện/TP, Tỉnh).
- **level 2**: không thấy chi tiết → lùi dần về cấp Huyện rồi cấp Tỉnh (tọa độ này sẽ được *jitter* thêm nhiễu ở cell phía sau).
- Không tìm được → để trống (`NaN`), sẽ bị `dropna` loại bỏ sau.

Kết quả là DataFrame `coordinate` có đúng các cột như file cũ (`Địa chỉ mới, Tọa độ, level, kinh độ, vĩ độ`) nên các cell phía sau chạy y nguyên.

> ⚠️ Nominatim giới hạn ~1 request/giây. Với ~1.300 địa chỉ, cell này chạy mất **~20–25 phút**. Có thể bỏ comment dòng `to_csv` cuối để lưu lại, lần sau khỏi chạy lại.

In [53]:
# Cài đặt thư viện geocoding (chỉ cần chạy 1 lần)
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# Nominatim (OpenStreetMap): miễn phí, KHÔNG cần API key.
# Bắt buộc đặt user_agent riêng và tuân thủ giới hạn 1 request/giây.
geolocator = Nominatim(user_agent=config.GEOCODER_USER_AGENT)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=config.GEOCODER_MIN_DELAY,
                      max_retries=2, swallow_exceptions=True)

# Cache để không truy vấn lặp lại cùng một chuỗi (vd các fallback cấp tỉnh)
_geo_cache = {}
def _query(q):
    if q not in _geo_cache:
        loc = geocode(q + ', Việt Nam', country_codes='vn')
        _geo_cache[q] = (loc.latitude, loc.longitude) if loc else None
    return _geo_cache[q]

def geocode_address(addr):
    """Trả về (vĩ độ, kinh độ, level). level=1 nếu khớp đầy đủ, =2 nếu phải fallback."""
    parts = [p.strip().title() for p in addr.split(',')]
    # Mức 1: địa chỉ đầy đủ
    res = _query(', '.join(parts))
    if res:
        return res[0], res[1], 1
    # Mức 2: lùi dần - bỏ phần đầu (Phường/Xã), rồi đến khi chỉ còn Tỉnh
    for i in range(1, len(parts)):
        res = _query(', '.join(parts[i:]))
        if res:
            return res[0], res[1], 2
    return None, None, None

ModuleNotFoundError: No module named 'geopy'

In [ ]:
# Geocode toàn bộ địa chỉ duy nhất trong df2 (giữ nguyên thứ tự để concat ăn khớp)
records = []
for n, addr in enumerate(df2['Địa chỉ'], start=1):
    lat, lon, level = geocode_address(addr)
    records.append({
        'Địa chỉ mới': addr,
        'Tọa độ': (lat, lon) if lat is not None else None,
        'level': level,
        'kinh độ': lon,   # kinh độ = longitude (~109)
        'vĩ độ': lat,     # vĩ độ  = latitude  (~13-23)
    })
    if n % 100 == 0:
        print(f'  ...đã geocode {n}/{len(df2)} địa chỉ')

coordinate = pd.DataFrame(records)
# Lưu lại để lần sau không phải chạy lại (tùy chọn):
# coordinate.to_csv('address_df_full.csv', index=False)
coordinate

In [ ]:
concat_df = pd.concat([df2,coordinate], axis = 1)
concat_df

,Phường/Xã,Huyện/TP,TENTINHTHANH,Địa chỉ,Địa chỉ mới,Tọa độ,level,kinh độ,vĩ độ
0,NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH,"NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH","NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH","(13.7930532, 109.1916057)",1,109.191606,13.793053
1,NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH","NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH","(13.7945583, 109.1813114)",1,109.181311,13.794558
2,NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH,"NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH","NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH","(13.8789863, 109.0686007)",1,109.068601,13.878986
3,TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH","TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH","(13.786352, 109.1482711)",1,109.148271,13.786352
4,DIÊU TRÌ,TUY PHƯỚC,BÌNH ĐỊNH,"DIÊU TRÌ,TUY PHƯỚC,BÌNH ĐỊNH","DIÊU TRÌ,TUY PHƯỚC,BÌNH ĐỊNH","(13.8071597, 109.1437149)",1,109.143715,13.807160
...,...,...,...,...,...,...,...,...,...
1252,ĐÔNG THẠNH,CẦN GIUỘC,LONG AN,"ĐÔNG THẠNH,CẦN GIUỘC,LONG AN","ĐÔNG THẠNH,CẦN GIUỘC,LONG AN","(10.5295518, 106.6724105)",1,106.672410,10.529552
1253,THANH TRÌ,THANH TRÌ,HÀ NỘI,"THANH TRÌ,THANH TRÌ,HÀ NỘI","THANH TRÌ,THANH TRÌ,HÀ NỘI","(20.94805855, 105.84967889687385)",1,105.849679,20.948059
1254,LỘC THỦY,PHÚ LỘC,THỪA THIÊN - HUẾ,"LỘC THỦY,PHÚ LỘC,THỪA THIÊN - HUẾ","LỘC THỦY,PHÚ LỘC,THỪA THIÊN - HUẾ","(16.2706984, 107.9277907)",1,107.927791,16.270698
1255,VĨNH THANH,RẠCH GIÁ,KIÊN GIANG,"VĨNH THANH,RẠCH GIÁ,KIÊN GIANG","VĨNH THANH,RẠCH GIÁ,KIÊN GIANG","(10.0153837, 105.0831127)",1,105.083113,10.015384
1256,PHƯỜNG 3,QUẬN 10,TP. HỒ CHÍ MINH,"PHƯỜNG 3,QUẬN 10,TP. HỒ CHÍ MINH","PHƯỜNG 3,QUẬN 10,TP. HỒ CHÍ MINH","(10.7770084, 106.6811613)",1,106.681161,10.777008

In [ ]:
df1['Địa chỉ'] = list(map(lambda x,y,z: x + ',' + y + ',' + z if (x != 'KHÔNG XÁC ĐỊNH') else
                                        y + ',' + z, df1['Phường/Xã'], df1['Huyện/TP'], df1['TENTINHTHANH']))
df1 = df1.drop(columns = ['TENPXA','TENQUANHUYEN'])
df1

,Tuổi,DANTOC,TENTINHTHANH,MAICD,CHANDOAN,NGAYVAO,NGAYRA,TONGCP,BHYT_TT,Thời gian điều trị,Vùng miền,Phường/Xã,Huyện/TP,Địa chỉ
0,28,Kinh,BÌNH ĐỊNH,S01.1;,Vết thương hở của mi mắt và vùng quanh mắt;,2016-01-01 00:55:00,2016-01-01 01:04:00,1.500000e+04,0.000000e+00,0.006250,Nam Trung Bộ,NHƠN BÌNH,QUI NHƠN,"NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH"
1,18,Kinh,BÌNH ĐỊNH,I20;,Cơn đau thắt ngực;,2016-01-01 01:37:00,2016-01-01 03:23:00,8.334650e+04,8.334650e+04,0.073611,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH"
2,36,Kinh,BÌNH ĐỊNH,J68.2;P71.0;,Viêm hô hấp trên;Hạ calci máu;,2016-01-01 03:31:00,2016-01-01 05:00:00,1.599990e+02,0.000000e+00,0.061806,Nam Trung Bộ,NHƠN LỘC,AN NHƠN,"NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH"
3,5,Kinh,BÌNH ĐỊNH,A91.A;,Sốt xuất huyết Dengue;,2015-12-29 20:25:00,2016-01-01 07:00:00,1.129380e+05,1.129380e+05,2.440972,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH"
4,5,Kinh,BÌNH ĐỊNH,A91;J00;,Sốt xuất huyết Dengue;Viêm Họng Cấp;,2015-12-25 08:44:00,2016-01-01 07:00:00,2.623950e+05,2.623950e+05,6.927778,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68757,73,Kinh,BÌNH ĐỊNH,Y84.1;D63.0;,Chạy thận nhân tạo;Thiếu máu trong bệnh suy th...,2016-12-01 08:11:00,2016-12-31 23:00:00,1.102239e+07,1.102239e+07,30.617361,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH"
68758,24,Dân tộc thiểu số,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:53:00,2016-12-31 23:00:00,1.359227e+07,1.359227e+07,42.671528,Nam Trung Bộ,BÌNH ĐỊNH,AN NHƠN,"BÌNH ĐỊNH,AN NHƠN,BÌNH ĐỊNH"
68759,42,Kinh,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:52:00,2016-12-31 23:00:00,1.021012e+07,1.021012e+07,42.672222,Nam Trung Bộ,NHƠN PHÚC,AN NHƠN,"NHƠN PHÚC,AN NHƠN,BÌNH ĐỊNH"
68760,40,Kinh,BÌNH ĐỊNH,Y84.1;J18;,Chạy thận nhân tạo;Viêm phổi;,2016-11-10 06:56:00,2016-12-31 23:00:00,1.734061e+07,1.734061e+07,51.669444,Nam Trung Bộ,MỸ THỌ,PHÙ MỸ,"MỸ THỌ,PHÙ MỸ,BÌNH ĐỊNH"
68761,58,Kinh,BÌNH ĐỊNH,I67;,Bệnh mạch máu não khác;,2016-12-31 22:26:00,2016-12-31 23:47:00,1.500000e+04,0.000000e+00,0.056250,Nam Trung Bộ,ĐỐNG ĐA,QUI NHƠN,"ĐỐNG ĐA,QUI NHƠN,BÌNH ĐỊNH"

In [ ]:
df1['Kinh độ'] = [concat_df[concat_df['Địa chỉ'] == x]['kinh độ'].iloc[0] for x in df1['Địa chỉ']]
df1['Vĩ độ'] = [concat_df[concat_df['Địa chỉ'] == x]['vĩ độ'].iloc[0] for x in df1['Địa chỉ']]
df1['level'] = [concat_df[concat_df['Địa chỉ'] == x]['level'].iloc[0] for x in df1['Địa chỉ']]

In [ ]:
# Đặt seed để bước jitter (cộng nhiễu ngẫu nhiên) tái lập được giữa các lần chạy
np.random.seed(config.RANDOM_SEED)
df1['Kinh độ'] = list(map(lambda x,y: x if (y == 1) else x + np.random.uniform(0.001,0.002),df1['Kinh độ'],df1['level']))
df1['Vĩ độ'] = list(map(lambda x,y: x if (y == 1) else x + np.random.uniform(0.001,0.002),df1['Vĩ độ'],df1['level']))

In [ ]:
df1 = df1.dropna(subset = ['Kinh độ'])
df1

,Tuổi,DANTOC,TENTINHTHANH,MAICD,CHANDOAN,NGAYVAO,NGAYRA,TONGCP,BHYT_TT,Thời gian điều trị,Vùng miền,Phường/Xã,Huyện/TP,Địa chỉ,Kinh độ,Vĩ độ,level
0,28,Kinh,BÌNH ĐỊNH,S01.1;,Vết thương hở của mi mắt và vùng quanh mắt;,2016-01-01 00:55:00,2016-01-01 01:04:00,1.500000e+04,0.000000e+00,0.006250,Nam Trung Bộ,NHƠN BÌNH,QUI NHƠN,"NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH",109.191606,13.793053,1
1,18,Kinh,BÌNH ĐỊNH,I20;,Cơn đau thắt ngực;,2016-01-01 01:37:00,2016-01-01 03:23:00,8.334650e+04,8.334650e+04,0.073611,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH",109.181311,13.794558,1
2,36,Kinh,BÌNH ĐỊNH,J68.2;P71.0;,Viêm hô hấp trên;Hạ calci máu;,2016-01-01 03:31:00,2016-01-01 05:00:00,1.599990e+02,0.000000e+00,0.061806,Nam Trung Bộ,NHƠN LỘC,AN NHƠN,"NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH",109.068601,13.878986,1
3,5,Kinh,BÌNH ĐỊNH,A91.A;,Sốt xuất huyết Dengue;,2015-12-29 20:25:00,2016-01-01 07:00:00,1.129380e+05,1.129380e+05,2.440972,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH",109.148271,13.786352,1
4,5,Kinh,BÌNH ĐỊNH,A91;J00;,Sốt xuất huyết Dengue;Viêm Họng Cấp;,2015-12-25 08:44:00,2016-01-01 07:00:00,2.623950e+05,2.623950e+05,6.927778,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH",109.181311,13.794558,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68757,73,Kinh,BÌNH ĐỊNH,Y84.1;D63.0;,Chạy thận nhân tạo;Thiếu máu trong bệnh suy th...,2016-12-01 08:11:00,2016-12-31 23:00:00,1.102239e+07,1.102239e+07,30.617361,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH",109.148271,13.786352,1
68758,24,Dân tộc thiểu số,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:53:00,2016-12-31 23:00:00,1.359227e+07,1.359227e+07,42.671528,Nam Trung Bộ,BÌNH ĐỊNH,AN NHƠN,"BÌNH ĐỊNH,AN NHƠN,BÌNH ĐỊNH",109.101382,13.887191,1
68759,42,Kinh,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:52:00,2016-12-31 23:00:00,1.021012e+07,1.021012e+07,42.672222,Nam Trung Bộ,NHƠN PHÚC,AN NHƠN,"NHƠN PHÚC,AN NHƠN,BÌNH ĐỊNH",109.030093,13.906113,1
68760,40,Kinh,BÌNH ĐỊNH,Y84.1;J18;,Chạy thận nhân tạo;Viêm phổi;,2016-11-10 06:56:00,2016-12-31 23:00:00,1.734061e+07,1.734061e+07,51.669444,Nam Trung Bộ,MỸ THỌ,PHÙ MỸ,"MỸ THỌ,PHÙ MỸ,BÌNH ĐỊNH",109.148393,14.220117,1
68761,58,Kinh,BÌNH ĐỊNH,I67;,Bệnh mạch máu não khác;,2016-12-31 22:26:00,2016-12-31 23:47:00,1.500000e+04,0.000000e+00,0.056250,Nam Trung Bộ,ĐỐNG ĐA,QUI NHƠN,"ĐỐNG ĐA,QUI NHƠN,BÌNH ĐỊNH",109.213253,13.786062,1

In [ ]:
df1['MAICD'].str[-1].value_counts()

MAICD
;    67850
3      106
5       24
7       16
2        9
1        7
0        6
4        5
9        2
8        1
Name: count, dtype: int64

In [ ]:
df1['MAICD'] = list(map(lambda x: x if x[-1] == ';' else x + ';',df1['MAICD']))

In [ ]:
df1['Số lượng bệnh/hỗ trợ y tế'] = [len(x) + 1 if (len(x) == 0) else len(x) for x in df1['MAICD'].str.split(';').str[0:-1]]
df1

,Tuổi,DANTOC,TENTINHTHANH,MAICD,CHANDOAN,NGAYVAO,NGAYRA,TONGCP,BHYT_TT,Thời gian điều trị,Vùng miền,Phường/Xã,Huyện/TP,Địa chỉ,Kinh độ,Vĩ độ,level,Số lượng bệnh/hỗ trợ y tế
0,28,Kinh,BÌNH ĐỊNH,S01.1;,Vết thương hở của mi mắt và vùng quanh mắt;,2016-01-01 00:55:00,2016-01-01 01:04:00,1.500000e+04,0.000000e+00,0.006250,Nam Trung Bộ,NHƠN BÌNH,QUI NHƠN,"NHƠN BÌNH,QUI NHƠN,BÌNH ĐỊNH",109.191606,13.793053,1,1
1,18,Kinh,BÌNH ĐỊNH,I20;,Cơn đau thắt ngực;,2016-01-01 01:37:00,2016-01-01 03:23:00,8.334650e+04,8.334650e+04,0.073611,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH",109.181311,13.794558,1,1
2,36,Kinh,BÌNH ĐỊNH,J68.2;P71.0;,Viêm hô hấp trên;Hạ calci máu;,2016-01-01 03:31:00,2016-01-01 05:00:00,1.599990e+02,0.000000e+00,0.061806,Nam Trung Bộ,NHƠN LỘC,AN NHƠN,"NHƠN LỘC,AN NHƠN,BÌNH ĐỊNH",109.068601,13.878986,1,2
3,5,Kinh,BÌNH ĐỊNH,A91.A;,Sốt xuất huyết Dengue;,2015-12-29 20:25:00,2016-01-01 07:00:00,1.129380e+05,1.129380e+05,2.440972,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH",109.148271,13.786352,1,1
4,5,Kinh,BÌNH ĐỊNH,A91;J00;,Sốt xuất huyết Dengue;Viêm Họng Cấp;,2015-12-25 08:44:00,2016-01-01 07:00:00,2.623950e+05,2.623950e+05,6.927778,Nam Trung Bộ,NHƠN PHÚ,QUI NHƠN,"NHƠN PHÚ,QUI NHƠN,BÌNH ĐỊNH",109.181311,13.794558,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68757,73,Kinh,BÌNH ĐỊNH,Y84.1;D63.0;,Chạy thận nhân tạo;Thiếu máu trong bệnh suy th...,2016-12-01 08:11:00,2016-12-31 23:00:00,1.102239e+07,1.102239e+07,30.617361,Nam Trung Bộ,TRẦN QUANG DIỆU,QUI NHƠN,"TRẦN QUANG DIỆU,QUI NHƠN,BÌNH ĐỊNH",109.148271,13.786352,1,2
68758,24,Dân tộc thiểu số,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:53:00,2016-12-31 23:00:00,1.359227e+07,1.359227e+07,42.671528,Nam Trung Bộ,BÌNH ĐỊNH,AN NHƠN,"BÌNH ĐỊNH,AN NHƠN,BÌNH ĐỊNH",109.101382,13.887191,1,1
68759,42,Kinh,BÌNH ĐỊNH,Y84.1;,Chạy thận nhân tạo;,2016-11-19 06:52:00,2016-12-31 23:00:00,1.021012e+07,1.021012e+07,42.672222,Nam Trung Bộ,NHƠN PHÚC,AN NHƠN,"NHƠN PHÚC,AN NHƠN,BÌNH ĐỊNH",109.030093,13.906113,1,1
68760,40,Kinh,BÌNH ĐỊNH,Y84.1;J18;,Chạy thận nhân tạo;Viêm phổi;,2016-11-10 06:56:00,2016-12-31 23:00:00,1.734061e+07,1.734061e+07,51.669444,Nam Trung Bộ,MỸ THỌ,PHÙ MỸ,"MỸ THỌ,PHÙ MỸ,BÌNH ĐỊNH",109.148393,14.220117,1,2
68761,58,Kinh,BÌNH ĐỊNH,I67;,Bệnh mạch máu não khác;,2016-12-31 22:26:00,2016-12-31 23:47:00,1.500000e+04,0.000000e+00,0.056250,Nam Trung Bộ,ĐỐNG ĐA,QUI NHƠN,"ĐỐNG ĐA,QUI NHƠN,BÌNH ĐỊNH",109.213253,13.786062,1,1

In [ ]:
def test():
  codes = df1['MAICD'].str.split(';').str[0:-1]
  codes_list = [x for code in codes for x in code]
  codes_list = list(set(codes_list))
  codes_list.sort()
  return codes_list

test()

['A00',
 'A01',
 'A01.0',
 'A02',
 'A02.0',
 'A02.1',
 'A02.8',
 'A03',
 'A03.9',
 'A04',
 'A04.0',
 'A04.5',
 'A04.8',
 'A04.9',
 'A05',
 'A05.1',
 'A06',
 'A06.0',
 'A06.1',
 'A06.2',
 'A06.3',
 'A06.4',
 'A06.5',
 'A06.6',
 'A08',
 'A08.0',
 'A08.3',
 'A08.5',
 'A09',
 'A09.0',
 'A09.9',
 'A15',
 'A15.0',
 'A15.1',
 'A15.2',
 'A15.3',
 'A15.4',
 'A15.6',
 'A16.0',
 'A16.1',
 'A16.2',
 'A16.4',
 'A17',
 'A17.0',
 'A18',
 'A18.0',
 'A18.3',
 'A19',
 'A20.3',
 'A20.7',
 'A21.0',
 'A23.1',
 'A24.3',
 'A25',
 'A26.7',
 'A28.1',
 'A28.8',
 'A31',
 'A31.8',
 'A32.0',
 'A32.1',
 'A32.9',
 'A33',
 'A35',
 'A37',
 'A37.9',
 'A39.0',
 'A39.1',
 'A40',
 'A40.9',
 'A41',
 'A41.0',
 'A41.2',
 'A41.4',
 'A41.8',
 'A41.9',
 'A42',
 'A48',
 'A48.3',
 'A48.4',
 'A48.8',
 'A49',
 'A49.0',
 'A49.8',
 'A49.9',
 'A54.2',
 'A54.5',
 'A55',
 'A57',
 'A58',
 'A68',
 'A68.0',
 'A68.9',
 'A69.0',
 'A74.0',
 'A75',
 'A75.2',
 'A75.9',
 'A77.2',
 'A78',
 'A79.0',
 'A79.8',
 'A80.3',
 'A81.1',
 'A82',
 'A82.9',
 'A83',
 'A83.0',
 'A83.8',
 'A85',
 'A85.8',
 'A86',
 'A87',
 'A87.8',
 'A87.9',
 'A90',
 'A91',
 'A91.1',
 'A91.A',
 'A91.B',
 'A91.C',
 'A91.C1',
 'A91.C2',
 'A91.C3',
 'A91.C4',
 'A92',
 'A93',
 'A93.1',
 'A94',
 'A98.8',
 'B00.1',
 'B00.2',
 'B00.4',
 'B00.5',
 'B01',
 'B01.2',
 'B02',
 'B02.2',
 'B02.3',
 'B02.7',
 'B08.4',
 'B08.4.1',
 'B08.4.2',
 'B08.4.2A',
 'B08.4.2B',
 'B08.5',
 'B15',
 'B15.0',
 'B15.9',
 'B16',
 'B16.2',
 'B17',
 'B17.0',
 'B17.1',
 'B17.8',
 'B18',
 'B18.0',
 'B18.1',
 'B18.2',
 'B19',
 'B19.0',
 'B19.9',
 'B20',
 'B20.1',
 'B20.3',
 'B20.5',
 'B20.6',
 'B22',
 'B22.2',
 'B25.0',
 'B25.1',
 'B26',
 'B26.0',
 'B26.1',
 'B26.8',
 'B27.0',
 'B27.8',
 'B30',
 'B30.0',
 'B30.3',
 'B30.9',
 'B33.0',
 'B34',
 'B34.0',
 'B35',
 'B35.0',
 'B35.1',
 'B35.2',
 'B36',
 'B36.8',
 'B37.0',
 'B37.6',
 'B39',
 'B43.1',
 'B43.2',
 'B47',
 'B47.0',
 'B48',
 'B48.8',
 'B49',
 'B50',
 'B50.0',
 'B51',
 'B51.8',
 'B53',
 'B58.2',
 'B65.3',
 'B65.8',
 'B66',
 'B66.0',
 'B66.8',
 'B68',
 'B74.4',
 'B77',
 'B83',
 'B87.4',
 'B90',
 'B94.1',
 'B99',
 'C00',
 'C00.3',
 'C00.8',
 'C01',
 'C02',
 'C02.0',
 'C02.6.1',
 'C02.9',
 'C03',
 'C03.0',
 'C03.1',
 'C03.1.1',
 'C04',
 'C04.8',
 'C04.9',
 'C05',
 'C05.0',
 'C05.1',
 'C05.2',
 'C05.8',
 'C06',
 'C06.0',
 'C06.1',
 'C06.2.1',
 'C06.9',
 'C07',
 'C08',
 'C08.0',
 'C08.1.1',
 'C08.9',
 'C09',
 'C09.0',
 'C10',
 'C11',
 'C11.0',
 'C11.9',
 'C12',
 'C13',
 'C13.9',
 'C14',
 'C14.2',
 'C14.8',
 'C15',
 'C15.0',
 'C15.1',
 'C15.2',
 'C15.4',
 'C15.9',
 'C16',
 'C16.0',
 'C16.1',
 'C16.3',
 'C16.9',
 'C17',
 'C17.1',
 'C18',
 'C18.0',
 'C18.1',
 'C18.2',
 'C18.6',
 'C18.9',
 'C20',
 'C20.1',
 'C21',
 'C21.0',
 'C21.1',
 'C21.8',
 'C22',
 'C22.0',
 'C22.1',
 'C22.2',
 'C22.3',
 'C22.4',
 'C22.9',
 'C23',
 'C23.1',
 'C24',
 'C24.0',
 'C24.1',
 'C25',
 'C25.0',
 'C25.1',
 'C25.2',
 'C25.4',
 'C25.8',
 'C26',
 'C26.1',
 'C30',
 'C30.0',
 'C31',
 'C31.0',
 'C31.1',
 'C32',
 'C32.9',
 'C33',
 'C34',
 'C37',
 'C38',
 'C38.0',
 'C38.1',
 'C39.0',
 'C40',
 'C40.0',
 'C41',
 'C41.1',
 'C41.2',
 'C41.3',
 'C41.9',
 'C43',
 'C43.2',
 'C43.8',
 'C44',
 'C44.9',
 'C45',
 'C45.0',
 'C45.1',
 'C46',
 'C46.0',
 'C46.1',
 'C46.2',
 'C47',
 'C48',
 'C48.0',
 'C48.2',
 'C49',
 'C49.4',
 'C50',
 'C50.1',
 'C50.9',
 'C51',
 'C51.0',
 'C52',
 'C53',
 'C53.1',
 'C53.9',
 'C54',
 'C54.0',
 'C54.1',
 'C54.8',
 'C55',
 'C56',
 'C56.1',
 'C57',
 'C57.4',
 'C60',
 'C60.1',
 'C60.8',
 'C60.9',
 'C61',
 'C61.1',
 'C62',
 'C62.1',
 'C63',
 'C63.1',
 'C64',
 'C65',
 'C66',
 'C67',
 'C67.4',
 'C67.5',
 'C67.7',
 'C67.9',
 'C68',
 'C68.8',
 'C68.9',
 'C69.2',
 'C69.6',
 'C69.8',
 'C69.9',
 'C70',
 'C70.0',
 'C70.1',
 'C71',
 'C71.5',
 'C71.6',
 'C71.9',
 'C72',
 'C72.0',
 'C72.2',
 'C73',
 'C74',
 'C74.0',
 'C74.9',
 'C76',
 'C76.0',
 'C76.2',
 'C77',
 'C77.0',
 'C77.3',
 'C77.4',
 'C77.8',
 'C77.9',
 'C78.1',
 'C78.5',
 'C78.6',
 'C78.7',
 'C79',
 'C79.0',
 'C79.5',
 'C79.7',
 'C81',
 'C81.2',
 'C81.9',
 'C82',
 'C82.9',
 'C83',
 'C83.1',
 'C84',
 'C84.0',
 'C85',
 'C85.0',
 'C85.9',
 'C90',
 'C90.0',
 'C90.1',
 'C91',
 'C91.0',
 'C91.1',
 'C91.2',
 'C91.7',
 'C92',
 'C92.0',
 'C92.1',
 'C94.4',
 'C94.6',
 'C94.7',
 'C95',
 'C95.0',
 'C95.1',
 'C96.8',
 'C97',
 'D00.2',
 'D01.3',
 'D01.4',
 'D01.5',
 'D02.0',
 'D04',
 'D04.4',
 'D07.1',
 'D07.4',
 'D07.5',
 'D09.0',
 'D09.2',
 'D09.7',
 'D10',
 'D10.1',
 'D10.4',
 'D11',
 'D11.0',
 'D11.7',
 'D12',
 'D12.0',
 'D12.1',
 'D12.2',
 'D12.5',
 'D12.6',
 'D12.8',
 'D12.9',
 'D13.1',
 'D13.2',
 'D13.4',
 'D13.5',
 'D13.6',
 'D14.3',
 'D15.1',
 'D15.2',
 'D15.9',
 'D16.5',
 'D16.6',
 'D16.7',
 'D17',
 'D17.1',
 'D17.3',
 'D17.5',
 'D17.6',
 'D17.7',
 'D17.9',
 'D18',
 'D18.0',
 'D18.1',
 'D20',
 'D20.0',
 'D21',
 'D22',
 'D23',
 'D23.2',
 'D23.4',
 'D24',
 'D25',
 'D25.9',
 'D26',
 'D26.0',
 'D26.9',
 'D27',
 'D28.2',
 'D29.0',
 'D29.1',
 'D29.2',
 'D29.3',
 'D29.4',
 'D30.0',
 'D30.2',
 'D30.3',
 'D30.4',
 'D32',
 'D33',
 'D33.2',
 'D33.3',
 'D33.4',
 'D34',
 'D35.0',
 'D35.6',
 'D35.8',
 'D36',
 'D36.0',
 'D36.1',
 'D37.2',
 'D37.4',
 'D37.5',
 'D37.6',
 'D38.0',
 'D38.2',
 'D39.1',
 'D40.0',
 'D40.1',
 'D43',
 'D43.0',
 'D43.4',
 'D44.0',
 'D44.1',
 'D44.4',
 'D46.0',
 'D46.1',
 'D46.2',
 'D46.4',
 'D46.7',
 'D47.1',
 'D47.3',
 'D50',
 'D50.0',
 'D50.8',
 'D50.9',
 'D53',
 'D53.0',
 'D53.1',
 'D56',
 'D56.1',
 'D56.3',
 'D56.8',
 'D57',
 'D57.0',
 'D57.8',
 'D58',
 'D58.9',
 'D59',
 'D59.1',
 'D59.8',
 'D60',
 'D60.0',
 'D60.8',
 'D61',
 'D61.0',
 'D61.1',
 'D61.2',
 'D61.3',
 'D61.9',
 'D62',
 'D63',
 'D63.0',
 'D64',
 'D64.0',
 'D64.3',
 'D64.4',
 'D64.9',
 'D66',
 'D68.3',
 'D68.8',
 'D68.9',
 'D69',
 'D69.0',
 'D69.1',
 'D69.2',
 'D69.3',
 'D69.4',
 'D69.5',
 'D69.6',
 'D69.8',
 'D69.9',
 'D72',
 'D73',
 'D73.1',
 'D73.2',
 'D73.3',
 'D73.4',
 'D73.5',
 'D73.8',
 'D74',
 'D74.0',
 'D75',
 'D75.1',
 'D75.2',
 'D76.1',
 'D76.2',
 'D77',
 'D80.5',
 'D81',
 'D82.4',
 'D89',
 'E01',
 'E01.0',
 'E02',
 'E03',
 'E03.0',
 'E03.1',
 'E03.5',
 'E03.8',
 'E03.9',
 'E04',
 'E04.0',
 'E04.1',
 'E04.8',
 'E04.9',
 'E05',
 'E05.1',
 'E05.5',
 'E07',
 'E07.9',
 'E10',
 'E10.0',
 'E10.9',
 'E11',
 'E11.0',
 'E11.3*',
 'E12',
 'E13',
 'E13.1',
 'E13.9',
 'E15',
 'E16.0',
 'E16.1',
 'E16.2',
 'E21.5',
 'E23.0',
 'E23.2',
 'E23.7',
 'E24',
 'E24.2',
 'E24.4',
 'E25.8',
 'E27',
 'E27.1',
 'E27.9',
 'E28.0',
 'E31.0',
 'E34',
 'E40',
 'E41',
 'E43',
 'E44',
 'E44.0',
 'E44.1',
 'E46.1',
 'E51.1',
 'E58',
 'E61.1',
 'E64.8',
 'E66.0',
 'E70.2',
 'E71.3',
 'E75',
 'E75.5',
 'E75.6',
 'E78.0',
 'E78.2',
 'E78.4',
 'E78.5',
 'E79.0',
 'E83.5',
 'E85',
 'E85.3',
 'E87',
 'E87.0',
 'E87.1',
 'E87.2',
 'E87.5',
 'E87.6',
 'E88',
 'E88.2',
 'E89.0',
 'E89.6',
 'F00',
 'F03',
 'F05',
 'F05.8',
 'F06',
 'F06.4',
 'F06.5',
 'F06.6',
 'F06.8',
 'F06.9',
 'F07',
 'F07.2',
 'F09',
 'F10',
 'F10.2',
 'F19',
 'F20',
 'F20.4',
 'F20.9',
 'F21',
 'F23',
 'F23.2',
 'F29',
 'F32',
 'F33',
 'F41',
 'F43.0',
 'F44.4',
 'F44.5',
 'F44.6',
 'F45',
 'F45.3',
 'F45.4',
 'F48',
 'F48.0',
 'F48.8',
 'F50.5',
 'F51',
 'F51.0',
 'F51.9',
 'F70',
 'F84.1',
 'F98.6',
 'F99',
 'G00',
 'G00.8',
 'G03.1',
 'G04',
 'G04.0',
 'G04.9',
 'G06.2',
 'G08',
 'G12',
 'G12.1',
 'G12.8',
 'G12.9',
 'G20',
 'G21',
 'G21.1',
 'G23',
 'G25.0',
 'G25.5',
 'G30',
 'G31',
 'G31.0',
 'G31.1',
 'G35',
 'G36.0',
 'G37.3',
 'G40',
 'G43',
 'G43.2',
 'G43.3',
 'G43.8',
 'G43.9',
 'G44',
 'G44.2',
 'G44.8',
 'G45',
 'G45.2',
 'G45.4',
 'G45.8',
 'G45.9',
 'G46',
 'G46.3',
 'G46.4',
 'G47',
 'G47.0',
 'G47.8',
 'G50',
 'G50.0',
 'G50.1',
 'G51',
 'G51.1',
 'G51.9',
 'G52',
 'G53',
 'G53.0',
 'G54',
 'G54.5',
 'G55',
 'G55.1',
 'G55.2',
 'G56',
 'G56.0',
 'G56.4',
 'G58.0',
 'G61',
 'G61.0',
 'G61.8',
 'G61.9',
 'G63.5',
 'G64',
 'G70.0',
 'G70.9',
 'G72.4',
 'G80',
 'G80.4',
 'G80.8',
 'G81',
 'G82.2',
 'G82.5',
 'G83.1',
 'G83.9',
 'G90.0',
 'G90.1',
 'G92',
 'G93.2',
 'G93.4',
 'G93.6',
 'G95',
 'G95.1',
 'G95.2',
 'G95.9',
 'G96.0',
 'H01',
 'H01.0',
 'H01.9',
 'H02',
 'H02.0',
 'H02.4',
 'H02.6',
 'H04',
 'H04.0',
 'H04.4',
 'H05',
 'H05.0',
 'H05.2',
 'H05.5',
 'H05.8',
 'H10',
 'H10.2',
 'H10.9',
 'H11',
 'H11.0',
 'H11.3',
 'H16',
 'H16.0',
 'H16.2',
 'H17',
 'H17.0',
 'H18',
 'H18.4',
 'H21.0',
 'H25',
 'H25.0',
 'H25.1',
 'H25.8',
 'H26',
 'H26.0',
 'H26.2',
 'H26.4',
 'H27',
 'H27.1',
 'H28',
 'H30',
 'H32',
 'H33',
 'H34.1',
 'H35',
 'H35.1',
 'H35.8',
 'H40',
 'H40.0',
 'H40.1',
 'H40.3',
 'H40.5',
 'H40.9',
 'H43.1',
 'H44',
 'H44.0',
 'H44.4',
 'H44.6',
 'H44.8',
 'H46',
 'H47',
 'H47.1',
 'H49.1',
 'H49.2',
 'H49.8',
 'H51.9',
 'H52.5',
 'H53.0',
 'H53.2',
 'H57',
 'H57.9',
 'H60',
 'H60.0',
 'H60.1',
 'H60.8',
 'H65',
 'H65.0',
 'H65.1',
 'H65.2',
 'H65.3',
 'H65.9',
 'H66',
 'H66.0',
 'H66.1',
 'H66.9',
 'H67',
 'H68',
 'H68.0',
 'H70.0',
 'H70.1',
 'H74.4',
 'H81',
 'H81.2',
 'H81.8',
 'H83',
 'H91.2',
 'H92.0',
 'H92.2',
 'H93',
 'H93.1',
 'H93.2',
 'I01',
 'I01.2',
 'I05.0',
 'I05.1',
 'I05.2',
 'I06.0',
 'I06.1',
 'I06.2',
 'I07.0',
 'I07.1',
 'I07.2',
 'I09',
 'I09.2',
 'I10',
 'I11',
 'I12',
 'I15.8',
 'I20',
 'I20.0',
 'I20.1',
 'I20.9',
 'I21',
 'I21.9',
 'I23.8',
 'I24',
 'I24.0',
 'I25',
 'I25.0',
 'I25.2',
 'I25.4',
 'I25.5',
 'I25.6',
 'I26.0',
 'I27',
 'I27.0',
 'I27.1',
 'I28',
 'I28.0',
 'I28.8',
 'I30',
 'I31',
 'I31.0',
 'I31.2',
 'I31.3',
 'I34.0',
 'I34.2',
 'I35.0',
 'I35.1',
 'I35.2',
 'I37.0',
 'I37.1',
 'I39.3',
 'I40',
 'I40.8',
 'I42.0',
 ...]

In [ ]:
!pip install roman
import roman

Collecting roman
  Downloading roman-5.2-py3-none-any.whl.metadata (4.3 kB)
Downloading roman-5.2-py3-none-any.whl (6.0 kB)
Installing collected packages: roman
Successfully installed roman-5.2

In [ ]:
def ICD(code):
  code = code[:3]
  code_range = [
      ('A00','B99'), ('C00','D49'), ('D50','D89'), ('E00','E89'), ('F00','F99'), ('G00','G99'), ('H00','H59'), ('H60','H95'),
      ('I00','I99'), ('J00','J99'), ('K00','K95'), ('L00','L99'), ('M00','M99'), ('N00','N99'), ('O00','O9A'), ('P00','P96'),
      ('Q00','Q99'), ('R00','R99'), ('S00','T98'), ('U00','U85'), ('V00','Y99'), ('Z00','Z99')
      ]
  for index in range(len(code_range)):
    if code >= code_range[index][0] and code <= code_range[index][1]:
      return roman.toRoman(index + 1)
  return None

In [ ]:
df1['MAICD'] = df1['MAICD'].str.split(';').str[0:-1]
df1['Danh mục'] = df1['MAICD'].apply(lambda x: [ICD(code) for code in x])
for i in range(1,23):
  df1['Số lượng danh mục bệnh %s'%(roman.toRoman(i))] = [x.count(roman.toRoman(i)) for x in df1['Danh mục']]

In [ ]:
df1

,Tuổi,DANTOC,TENTINHTHANH,MAICD,CHANDOAN,NGAYVAO,NGAYRA,TONGCP,BHYT_TT,Thời gian điều trị,...,Số lượng danh mục bệnh XIII,Số lượng danh mục bệnh XIV,Số lượng danh mục bệnh XV,Số lượng danh mục bệnh XVI,Số lượng danh mục bệnh XVII,Số lượng danh mục bệnh XVIII,Số lượng danh mục bệnh XIX,Số lượng danh mục bệnh XX,Số lượng danh mục bệnh XXI,Số lượng danh mục bệnh XXII
0,28,Kinh,BÌNH ĐỊNH,[S01.1],Vết thương hở của mi mắt và vùng quanh mắt;,2016-01-01 00:55:00,2016-01-01 01:04:00,1.500000e+04,0.000000e+00,0.006250,...,0,0,0,0,0,0,1,0,0,0
1,18,Kinh,BÌNH ĐỊNH,[I20],Cơn đau thắt ngực;,2016-01-01 01:37:00,2016-01-01 03:23:00,8.334650e+04,8.334650e+04,0.073611,...,0,0,0,0,0,0,0,0,0,0
2,36,Kinh,BÌNH ĐỊNH,"[J68.2, P71.0]",Viêm hô hấp trên;Hạ calci máu;,2016-01-01 03:31:00,2016-01-01 05:00:00,1.599990e+02,0.000000e+00,0.061806,...,0,0,0,1,0,0,0,0,0,0
3,5,Kinh,BÌNH ĐỊNH,[A91.A],Sốt xuất huyết Dengue;,2015-12-29 20:25:00,2016-01-01 07:00:00,1.129380e+05,1.129380e+05,2.440972,...,0,0,0,0,0,0,0,0,0,0
4,5,Kinh,BÌNH ĐỊNH,"[A91, J00]",Sốt xuất huyết Dengue;Viêm Họng Cấp;,2015-12-25 08:44:00,2016-01-01 07:00:00,2.623950e+05,2.623950e+05,6.927778,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68757,73,Kinh,BÌNH ĐỊNH,"[Y84.1, D63.0]",Chạy thận nhân tạo;Thiếu máu trong bệnh suy th...,2016-12-01 08:11:00,2016-12-31 23:00:00,1.102239e+07,1.102239e+07,30.617361,...,0,0,0,0,0,0,0,0,1,0
68758,24,Dân tộc thiểu số,BÌNH ĐỊNH,[Y84.1],Chạy thận nhân tạo;,2016-11-19 06:53:00,2016-12-31 23:00:00,1.359227e+07,1.359227e+07,42.671528,...,0,0,0,0,0,0,0,0,1,0
68759,42,Kinh,BÌNH ĐỊNH,[Y84.1],Chạy thận nhân tạo;,2016-11-19 06:52:00,2016-12-31 23:00:00,1.021012e+07,1.021012e+07,42.672222,...,0,0,0,0,0,0,0,0,1,0
68760,40,Kinh,BÌNH ĐỊNH,"[Y84.1, J18]",Chạy thận nhân tạo;Viêm phổi;,2016-11-10 06:56:00,2016-12-31 23:00:00,1.734061e+07,1.734061e+07,51.669444,...,0,0,0,0,0,0,0,0,1,0
68761,58,Kinh,BÌNH ĐỊNH,[I67],Bệnh mạch máu não khác;,2016-12-31 22:26:00,2016-12-31 23:47:00,1.500000e+04,0.000000e+00,0.056250,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
model_df = df1.copy().drop(columns = ['MAICD','Danh mục','TENTINHTHANH','CHANDOAN','Phường/Xã','Huyện/TP','NGAYRA','BHYT_TT','Địa chỉ','level','Danh mục'])
model_df['NGAYVAO'] = model_df['NGAYVAO'].dt.month
model_df = model_df.rename(columns = {'NGAYVAO': 'Tháng nhập viện'})
model_df = model_df[~((model_df['Vĩ độ'] > 20) & (model_df['Vùng miền'] == 'Nam Trung Bộ'))]
model_df

,Tuổi,DANTOC,Tháng nhập viện,TONGCP,Thời gian điều trị,Vùng miền,Kinh độ,Vĩ độ,Số lượng bệnh/hỗ trợ y tế,Số lượng danh mục bệnh I,...,Số lượng danh mục bệnh XIII,Số lượng danh mục bệnh XIV,Số lượng danh mục bệnh XV,Số lượng danh mục bệnh XVI,Số lượng danh mục bệnh XVII,Số lượng danh mục bệnh XVIII,Số lượng danh mục bệnh XIX,Số lượng danh mục bệnh XX,Số lượng danh mục bệnh XXI,Số lượng danh mục bệnh XXII
0,28,Kinh,1,1.500000e+04,0.006250,Nam Trung Bộ,109.191606,13.793053,1,0,...,0,0,0,0,0,0,1,0,0,0
1,18,Kinh,1,8.334650e+04,0.073611,Nam Trung Bộ,109.181311,13.794558,1,0,...,0,0,0,0,0,0,0,0,0,0
2,36,Kinh,1,1.599990e+02,0.061806,Nam Trung Bộ,109.068601,13.878986,2,0,...,0,0,0,1,0,0,0,0,0,0
3,5,Kinh,12,1.129380e+05,2.440972,Nam Trung Bộ,109.148271,13.786352,1,1,...,0,0,0,0,0,0,0,0,0,0
4,5,Kinh,12,2.623950e+05,6.927778,Nam Trung Bộ,109.181311,13.794558,2,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68757,73,Kinh,12,1.102239e+07,30.617361,Nam Trung Bộ,109.148271,13.786352,2,0,...,0,0,0,0,0,0,0,0,1,0
68758,24,Dân tộc thiểu số,11,1.359227e+07,42.671528,Nam Trung Bộ,109.101382,13.887191,1,0,...,0,0,0,0,0,0,0,0,1,0
68759,42,Kinh,11,1.021012e+07,42.672222,Nam Trung Bộ,109.030093,13.906113,1,0,...,0,0,0,0,0,0,0,0,1,0
68760,40,Kinh,11,1.734061e+07,51.669444,Nam Trung Bộ,109.148393,14.220117,2,0,...,0,0,0,0,0,0,0,0,1,0
68761,58,Kinh,12,1.500000e+04,0.056250,Nam Trung Bộ,109.213253,13.786062,1,0,...,0,0,0,0,0,0,0,0,0,0

### Lưu bảng dữ liệu cho mô hình
Lưu `model_df` ra cả `.pkl` (giữ kiểu dữ liệu) và `.csv` (dễ xem).

In [ ]:
config.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
model_df.to_pickle(config.MODEL_DF_PKL)
model_df.to_csv(config.MODEL_DF_CSV, index=False)
print('Đã lưu', model_df.shape, '->', config.MODEL_DF_PKL, '&', config.MODEL_DF_CSV)